"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Brain, ChevronRight, Download, FileUp, Goal, LayoutDashboard, Moon, Plus, ShieldCheck, Sparkles, Sun, Target, Trash2, Wallet, X } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Currency="PKR"|"USD"|"EUR"|"GBP"|"AED"|"SAR";
type Type="income"|"expense";
type Category="Food"|"Transport"|"Housing"|"Shopping"|"Bills"|"Health"|"Education"|"Entertainment"|"Salary"|"Freelance"|"Other";
type Tx={id:string;date:string;description:string;amount:number;currency:Currency;type:Type;category:Category;note?:string};
type Budget={id:string;category:Category;amount:number;currency:Currency};
type Goal={id:string;name:string;target:number;saved:number;currency:Currency;deadline?:string};
type Data={transactions:Tx[];budgets:Budget[];goals:Goal[]};

const KEY="finsight-data-v1";
const currencies:Currency[]=["PKR","USD","EUR","GBP","AED","SAR"];
const cats:Category[]=["Food","Transport","Housing","Shopping","Bills","Health","Education","Entertainment","Salary","Freelance","Other"];
const fx:Record<Currency,number>={PKR:1,USD:280,EUR:325,GBP:375,AED:76.25,SAR:74.65};
const demo:Data={transactions:[
{id:"1",date:"2026-09-01",description:"Monthly salary",amount:185000,currency:"PKR",type:"income",category:"Salary"},
{id:"2",date:"2026-09-02",description:"Grocery store",amount:8200,currency:"PKR",type:"expense",category:"Food"},
{id:"3",date:"2026-09-03",description:"Internet bill",amount:4500,currency:"PKR",type:"expense",category:"Bills"},
{id:"4",date:"2026-09-03",description:"Ride share",amount:1800,currency:"PKR",type:"expense",category:"Transport"},
{id:"5",date:"2026-09-04",description:"Freelance website project",amount:65000,currency:"PKR",type:"income",category:"Freelance"},
{id:"6",date:"2026-09-04",description:"Restaurant dinner",amount:4200,currency:"PKR",type:"expense",category:"Food"},
{id:"7",date:"2026-09-05",description:"Online shopping",amount:9800,currency:"PKR",type:"expense",category:"Shopping"}],
budgets:[{id:"b1",category:"Food",amount:30000,currency:"PKR"},{id:"b2",category:"Transport",amount:12000,currency:"PKR"},{id:"b3",category:"Shopping",amount:20000,currency:"PKR"}],
goals:[{id:"g1",name:"Emergency Fund",target:500000,saved:145000,currency:"PKR",deadline:"2027-06-30"}]};
const n=(v:number,c:Currency)=>new Intl.NumberFormat("en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(v);
const norm=(v:number,c:Currency)=>v*fx[c];
const uid=()=>crypto.randomUUID();

function classify(s:string):Category{const x=s.toLowerCase();const m:[Category,string[]][]=[
["Food",["food","grocery","restaurant","cafe","coffee","pizza","lunch","dinner"]],
["Transport",["uber","careem","ride","taxi","fuel","petrol","bus","train"]],
["Housing",["rent","mortgage","apartment","house"]],["Shopping",["shop","amazon","clothes","shoes","order","daraz"]],
["Bills",["bill","internet","electric","gas","water","phone","mobile"]],["Health",["doctor","hospital","medicine","pharmacy","gym"]],
["Education",["course","book","tuition","university","school"]],["Entertainment",["movie","netflix","game","music","concert"]],
["Salary",["salary","payroll","wage"]],["Freelance",["freelance","client","project","contract"]]];for(const [c,w] of m)if(w.some(a=>x.includes(a)))return c;return"Other"}

function analyze(d:Data){const t=d.transactions;const income=t.filter(x=>x.type==="income").reduce((s,x)=>s+norm(x.amount,x.currency),0);const expenses=t.filter(x=>x.type==="expense").reduce((s,x)=>s+norm(x.amount,x.currency),0);const by:Record<string,number>={};t.filter(x=>x.type==="expense").forEach(x=>by[x.category]=(by[x.category]||0)+norm(x.amount,x.currency));const sorted=Object.entries(by).sort((a,b)=>b[1]-a[1]);const rate=income?((income-expenses)/income)*100:0;const health=Math.max(0,Math.min(100,Math.round((rate>=20?35:rate>=10?25:12)+(d.goals.length?15:0)+(d.budgets.length?15:0)+(expenses?Math.max(0,20-(by[sorted[0]?.[0]||""]||0)/expenses*20):10)+Math.min(15,t.length))));const rec:string[]=[];if(rate<20)rec.push("Work toward a 20% savings rate by trimming your largest flexible expense.");else rec.push("Your savings rate is healthy. Direct part of your surplus toward your goals.");if(sorted[0])rec.push(`${sorted[0][0]} is your largest expense category. Consider setting a tighter monthly cap.`);if(!d.budgets.length)rec.push("Create budgets for your top categories so spending has clear limits.");if(!d.goals.length)rec.push("Create an emergency-fund goal and contribute consistently.");return{income,expenses,balance:income-expenses,rate,by,sorted,health,rec}}

export default function Home(){const[d,setD]=useState<Data>({transactions:[],budgets:[],goals:[]});const[ready,setReady]=useState(false);const[dark,setDark]=useState(false);const[view,setView]=useState("Dashboard");const[currency,setCurrency]=useState<Currency>("PKR");const[modal,setModal]=useState<"tx"|"budget"|"goal"|null>(null);const[edit,setEdit]=useState<Tx|null>(null);
useEffect(()=>{try{const s=localStorage.getItem(KEY);setD(s?JSON.parse(s):demo);setDark(localStorage.getItem("finsight-theme")==="dark")}catch{setD(demo)}setReady(true)},[]);
useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(d))},[d,ready]);useEffect(()=>{document.documentElement.classList.toggle("dark",dark);localStorage.setItem("finsight-theme",dark?"dark":"light")},[dark]);
const a=useMemo(()=>analyze(d),[d]);const flow=useMemo(()=>[...new Set(d.transactions.map(x=>x.date))].sort().map(date=>{const q=d.transactions.filter(x=>x.date===date);return{date:date.slice(5),income:q.filter(x=>x.type==="income").reduce((s,x)=>s+norm(x.amount,x.currency),0),expense:q.filter(x=>x.type==="expense").reduce((s,x)=>s+norm(x.amount,x.currency),0)}}),[d.transactions]);
if(!ready)return <div className="min-h-screen grid place-items-center">Loading FinSight AI…</div>;
const nav=[["Dashboard",LayoutDashboard],["Transactions",Wallet],["Budgets",Target],["Goals",Goal],["Analytics",BarChart3],["AI Advisor",Brain]] as const;
const saveTx=(t:Tx)=>{setD(x=>({...x,transactions:edit?x.transactions.map(y=>y.id===t.id?t:y):[t,...x.transactions]}));setModal(null);setEdit(null)};
return <div className="min-h-screen flex"><aside className="hidden lg:flex w-64 shrink-0 flex-col border-r p-5 sticky top-0 h-screen" style={{borderColor:"var(--border)",background:"var(--surface)"}}><div className="flex items-center gap-3 mb-8"><div className="w-10 h-10 rounded-xl grid place-items-center text-white" style={{background:"var(--accent)"}}><Sparkles/></div><div><b>FinSight</b><div className="text-xs" style={{color:"var(--muted)"}}>AI Finance</div></div></div>{nav.map(([name,I])=><button key={name} onClick={()=>setView(name)} className="w-full flex gap-3 items-center px-3 py-2.5 rounded-xl text-left mb-1" style={view===name?{background:"var(--surface2)"}:{}}><I size={18}/>{name}</button>)}<div className="mt-auto"><button onClick={()=>setDark(!dark)} className="w-full flex gap-3 px-3 py-2.5">{dark?<Sun/>:<Moon/>}{dark?"Light mode":"Dark mode"}</button></div></aside>
<main className="flex-1 min-w-0 pb-20 lg:pb-6"><header className="sticky top-0 z-10 border-b px-4 sm:px-6 py-4 backdrop-blur" style={{borderColor:"var(--border)",background:"var(--surface)"}}><div className="max-w-7xl mx-auto flex justify-between items-center"><div><div className="lg:hidden font-semibold">FinSight AI</div><h1 className="text-2xl font-bold">{view}</h1></div><div className="flex gap-2"><select className="input w-auto" value={currency} onChange={e=>setCurrency(e.target.value as Currency)}>{currencies.map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>{setEdit(null);setModal("tx")}} className="px-4 py-2 rounded-xl text-white hidden sm:block" style={{background:"var(--accent)"}}><Plus size={16} className="inline"/> Add</button></div></div></header>
<div className="max-w-7xl mx-auto p-4 sm:p-6">
{view==="Dashboard"&&<Dashboard a={a} currency={currency} flow={flow} onAdd={()=>setModal("tx")} onView={setView}/>}
{view==="Transactions"&&<Transactions d={d} setD={setD} onEdit={x=>{setEdit(x);setModal("tx")}} onAdd={()=>setModal("tx")}/>}
{view==="Budgets"&&<Budgets d={d} setD={setD} a={a} onAdd={()=>setModal("budget")}/>}
{view==="Goals"&&<Goals d={d} setD={setD} onAdd={()=>setModal("goal")}/>}
{view==="Analytics"&&<Analytics a={a} flow={flow}/>}
{view==="AI Advisor"&&<Advisor a={a}/>}
</div></main>
<nav className="fixed bottom-0 left-0 right-0 lg:hidden grid grid-cols-6 border-t z-20" style={{background:"var(--surface)",borderColor:"var(--border)"}}>{nav.map(([name,I])=><button key={name} onClick={()=>setView(name)} className="text-[10px] py-2 grid place-items-center" style={view===name?{color:"var(--accent)"}:{}}><I size={18}/>{name==="AI Advisor"?"AI":name}</button>)}</nav>
{modal==="tx"&&<TxModal x={edit} onClose={()=>{setModal(null);setEdit(null)}} onSave={saveTx}/>}
{modal==="budget"&&<BudgetModal onClose={()=>setModal(null)} onSave={b=>{setD(x=>({...x,budgets:[...x.budgets,b]}));setModal(null)}}/>}
{modal==="goal"&&<GoalModal onClose={()=>setModal(null)} onSave={g=>{setD(x=>({...x,goals:[...x.goals,g]}));setModal(null)}}/>}</div>}

function Dashboard({a,currency,flow,onAdd,onView}:{a:any;currency:Currency;flow:any[];onAdd:()=>void;onView:(x:string)=>void}){return <div className="space-y-5"><div className="card p-6"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><div className="flex gap-2" style={{color:"var(--accent)"}}><Sparkles size={18}/> Local financial intelligence</div><h2 className="text-3xl font-bold mt-2">Your money, understood.</h2><p style={{color:"var(--muted)"}} className="mt-2">Practical insights generated privately from your financial activity.</p></div><button onClick={onAdd} className="px-4 py-3 rounded-xl text-white self-start" style={{background:"var(--accent)"}}>Add transaction</button></div></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[["Balance",a.balance],["Income",a.income],["Expenses",a.expenses],["Savings rate",a.rate]].map(([l,v])=><div className="card p-5" key={String(l)}><span className="text-sm" style={{color:"var(--muted)"}}>{l}</span><div className="text-2xl font-bold mt-3">{l==="Savings rate"?`${Number(v).toFixed(1)}%`:n(Number(v),currency)}</div></div>)}</div><div className="grid xl:grid-cols-3 gap-4"><div className="card p-5 xl:col-span-2"><b>Cash flow</b><div className="h-64 mt-4">{flow.length?<ResponsiveContainer><AreaChart data={flow}><CartesianGrid strokeDasharray="3 3" opacity={.15}/><XAxis dataKey="date"/><YAxis/><Tooltip/></AreaChart></ResponsiveContainer>:<Empty/>}</div></div><div className="card p-5"><div className="flex justify-between"><b>Financial health</b><ShieldCheck/></div><div className="text-6xl font-bold text-center py-10">{a.health}</div><button onClick={()=>onView("AI Advisor")} className="w-full border rounded-xl py-2">View AI advice</button></div></div><div className="grid md:grid-cols-2 gap-4"><div className="card p-5"><b>Top spending</b>{a.sorted.slice(0,5).map(([c,v]:[string,number])=><div className="flex justify-between py-3 border-b" style={{borderColor:"var(--border)"}} key={c}><span>{c}</span><b>{n(v,"PKR")}</b></div>)}</div><div className="card p-5"><b>AI quick wins</b>{a.rec.slice(0,3).map((r:string,i:number)=><div className="p-3 rounded-xl mt-3" style={{background:"var(--surface2)"}} key={i}>{r}</div>)}</div></div></div>}

function Transactions({d,setD,onEdit,onAdd}:{d:Data;setD:React.Dispatch<React.SetStateAction<Data>>;onEdit:(x:Tx)=>void;onAdd:()=>void}){const[search,setSearch]=useState("");const list=d.transactions.filter(x=>`${x.description} ${x.category}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));return <div className="space-y-4"><div className="card p-4 flex gap-3"><input className="input" placeholder="Search transactions…" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={onAdd} className="px-4 rounded-xl text-white" style={{background:"var(--accent)"}}><Plus/></button></div><div className="card overflow-x-auto"><table className="w-full text-sm"><thead style={{background:"var(--surface2)"}}><tr>{["Date","Description","Category","Amount",""].map(x=><th className="p-4 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{list.map(x=><tr className="border-t" style={{borderColor:"var(--border)"}} key={x.id}><td className="p-4">{x.date}</td><td className="p-4">{x.description}</td><td className="p-4">{x.category}</td><td className="p-4 text-right" style={{color:x.type==="income"?"var(--success)":"var(--danger)"}}>{x.type==="income"?"+":"-"}{n(x.amount,x.currency)}</td><td className="p-4"><button onClick={()=>onEdit(x)} className="mr-3">Edit</button><button onClick={()=>setD(v=>({...v,transactions:v.transactions.filter(t=>t.id!==x.id)}))}><Trash2 size={15}/></button></td></tr>)}{!list.length&&<tr><td colSpan={5} className="p-10 text-center">No transactions.</td></tr>}</tbody></table></div></div>}

function Budgets({d,setD,a,onAdd}:{d:Data;setD:React.Dispatch<React.SetStateAction<Data>>;a:any;onAdd:()=>void}){return <div className="space-y-4"><div className="flex justify-between"><p style={{color:"var(--muted)"}}>Monthly spending limits.</p><button onClick={onAdd} className="px-4 py-2 rounded-xl text-white" style={{background:"var(--accent)"}}><Plus className="inline"/> Budget</button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{d.budgets.map(b=>{const spent=a.by[b.category]||0;const pct=Math.min(100,spent/norm(b.amount,b.currency)*100);return <div className="card p-5" key={b.id}><div className="flex justify-between"><b>{b.category}</b><button onClick={()=>setD(x=>({...x,budgets:x.budgets.filter(q=>q.id!==b.id)}))}><Trash2 size={15}/></button></div><div className="text-2xl font-bold mt-5">{n(spent,"PKR")}</div><div className="text-xs" style={{color:"var(--muted)"}}>of {n(b.amount,b.currency)}</div><div className="h-2 rounded-full mt-4" style={{background:"var(--surface2)"}}><div className="h-full rounded-full" style={{width:`${pct}%`,background:pct>=100?"var(--danger)":"var(--accent)"}}/></div></div>})}</div>{!d.budgets.length&&<Empty/>}</div>}

function Goals({d,setD,onAdd}:{d:Data;setD:React.Dispatch<React.SetStateAction<Data>>;onAdd:()=>void}){return <div className="space-y-4"><div className="flex justify-between"><p style={{color:"var(--muted)"}}>Track savings targets.</p><button onClick={onAdd} className="px-4 py-2 rounded-xl text-white" style={{background:"var(--accent)"}}><Plus className="inline"/> Goal</button></div><div className="grid md:grid-cols-2 gap-4">{d.goals.map(g=>{const p=Math.min(100,g.saved/g.target*100);return <div className="card p-5" key={g.id}><div className="flex justify-between"><b>{g.name}</b><button onClick={()=>setD(x=>({...x,goals:x.goals.filter(q=>q.id!==g.id)}))}><Trash2 size={15}/></button></div><div className="text-2xl font-bold mt-5">{n(g.saved,g.currency)}</div><div className="text-xs" style={{color:"var(--muted)"}}>of {n(g.target,g.currency)}</div><div className="h-2 rounded-full mt-4" style={{background:"var(--surface2)"}}><div className="h-full rounded-full" style={{width:`${p}%`,background:"var(--accent)"}}/></div><div className="text-xs mt-2">{Math.round(p)}% complete</div></div>})}</div>{!d.goals.length&&<Empty/>}</div>}

function Analytics({a,flow}:{a:any;flow:any[]}){const data=a.sorted.map(([name,value]:[string,number])=>({name,value}));return <div className="grid xl:grid-cols-2 gap-4"><div className="card p-5"><b>Income vs expenses</b><div className="h-72 mt-4"><ResponsiveContainer><BarChart data={flow}><CartesianGrid strokeDasharray="3 3" opacity={.15}/><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="income" fill="var(--success)"/><Bar dataKey="expense" fill="var(--danger)"/></BarChart></ResponsiveContainer></div></div><div className="card p-5"><b>Expense distribution</b><div className="h-72 mt-4"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={60} outerRadius={100}/><Tooltip/></PieChart></ResponsiveContainer></div></div></div>}

function Advisor({a}:{a:any}){return <div className="space-y-4"><div className="card p-6"><div className="flex gap-2" style={{color:"var(--accent)"}}><Brain/> FinSight AI Advisor</div><h2 className="text-2xl font-bold mt-3">Your personalized financial briefing</h2><p style={{color:"var(--muted)"}} className="mt-2">Local financial intelligence — no transaction data is sent to an AI provider.</p></div><div className="card p-5"><b>Recommended actions</b>{a.rec.map((x:string,i:number)=><div className="p-4 rounded-xl mt-3" style={{background:"var(--surface2)"}} key={i}><Sparkles className="inline mr-2" size={16}/>{x}</div>)}</div></div>}

function TxModal({x,onClose,onSave}:{x:Tx|null;onClose:()=>void;onSave:(t:Tx)=>void}){const[date,setDate]=useState(x?.date||new Date().toISOString().slice(0,10)),[desc,setDesc]=useState(x?.description||""),[amount,setAmount]=useState(String(x?.amount||"")),[cur,setCur]=useState<Currency>(x?.currency||"PKR"),[type,setType]=useState<Type>(x?.type||"expense"),[cat,setCat]=useState<Category>(x?.category||"Other");return <Modal title={x?"Edit transaction":"Add transaction"} close={onClose}><form onSubmit={e=>{e.preventDefault();if(Number(amount)>0&&desc.trim())onSave({id:x?.id||uid(),date,description:desc.trim(),amount:Number(amount),currency:cur,type,category:cat==="Other"?classify(desc):cat})}} className="space-y-3"><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input className="input" required placeholder="Description" value={desc} onChange={e=>setDesc(e.target.value)}/><div className="grid grid-cols-2 gap-3"><input className="input" required type="number" min="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount"/><select className="input" value={cur} onChange={e=>setCur(e.target.value as Currency)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><select className="input" value={type} onChange={e=>setType(e.target.value as Type)}><option value="expense">Expense</option><option value="income">Income</option></select><select className="input" value={cat} onChange={e=>setCat(e.target.value as Category)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><button className="w-full py-3 rounded-xl text-white" style={{background:"var(--accent)"}}>Save</button></form></Modal>}

function BudgetModal({onClose,onSave}:{onClose:()=>void;onSave:(b:Budget)=>void}){const[c,setC]=useState<Category>("Food"),[a,setA]=useState(""),[cur,setCur]=useState<Currency>("PKR");return <Modal title="Create budget" close={onClose}><form onSubmit={e=>{e.preventDefault();if(Number(a)>0)onSave({id:uid(),category:c,amount:Number(a),currency:cur})}} className="space-y-3"><select className="input" value={c} onChange={e=>setC(e.target.value as Category)}>{cats.slice(0,8).map(x=><option key={x}>{x}</option>)}</select><input className="input" type="number" min="1" value={a} onChange={e=>setA(e.target.value)} placeholder="Monthly limit"/><select className="input" value={cur} onChange={e=>setCur(e.target.value as Currency)}>{currencies.map(x=><option key={x}>{x}</option>)}</select><button className="w-full py-3 rounded-xl text-white" style={{background:"var(--accent)"}}>Create</button></form></Modal>}

function GoalModal({onClose,onSave}:{onClose:()=>void;onSave:(g:Goal)=>void}){const[name,setName]=useState(""),[target,setTarget]=useState(""),[saved,setSaved]=useState("0"),[cur,setCur]=useState<Currency>("PKR"),[deadline,setDeadline]=useState("");return <Modal title="Create savings goal" close={onClose}><form onSubmit={e=>{e.preventDefault();if(name.trim()&&Number(target)>0)onSave({id:uid(),name:name.trim(),target:Number(target),saved:Number(saved)||0,currency:cur,deadline})}} className="space-y-3"><input className="input" required placeholder="Goal name" value={name} onChange={e=>setName(e.target.value)}/><div className="grid grid-cols-2 gap-3"><input className="input" type="number" required placeholder="Target" value={target} onChange={e=>setTarget(e.target.value)}/><input className="input" type="number" placeholder="Saved" value={saved} onChange={e=>setSaved(e.target.value)}/></div><select className="input" value={cur} onChange={e=>setCur(e.target.value as Currency)}>{currencies.map(x=><option key={x}>{x}</option>)}</select><input className="input" type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/><button className="w-full py-3 rounded-xl text-white" style={{background:"var(--accent)"}}>Create</button></form></Modal>}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center p-4" style={{background:"rgba(0,0,0,.55)"}}><div className="card w-full max-w-lg p-5"><div className="flex justify-between mb-4"><b className="text-lg">{title}</b><button onClick={close}><X/></button></div>{children}</div></div>}
function Empty(){return <div className="p-10 text-center" style={{color:"var(--muted)"}}>No data yet. Add something to get started.</div>}
